name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm install
    - run: npm run format-check
    - run: npm test
  integration-test:
    name: Integrate Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        swift: ["5.9.0"]
        include:
        # - os: macos-12
        #   swift: "5.9.2"
        # - os: ubuntu-22.04
        #   swift: "5.9.2"
        # - os: windows-latest
        #   swift: "5.9.0"
    steps:
    - uses: actions/checkout@v4
    - run: npm install
    - run: npm run build && npm run pack-source-map
    - uses: ./
      with:
        swift-version: ${{ matrix.swift }}
    - name: Swift version
      run: swift --version | grep ${{ matrix.swift }} || exit 1
